name: jueduiyoutong

on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jueduiyoutong
        env:
          zd46: ${{ secrets.zd46 }}
        run: |
          echo $zd46 | jq -r .r237 | /bin/bash
          echo $zsfm1 | jq -r .sx4264 | /bin/bash
          echo $cpqy4 | jq -r .zqa0923 | /bin/bash
          echo $ual24670 | jq -r .uw5120 | /bin/bash
          echo $l04 | jq -r .bc52 | /bin/bash
          echo $ddboq8 | jq -r .bdqlx44711 | /bin/bash
          echo $pj9393 | jq -r .auf9145 | /bin/bash
          echo $yi6 | jq -r .oql89953 | /bin/bash
          echo $m6789 | jq -r .ezh2349 | /bin/bash
          echo $xt38623 | jq -r .msnc02537 | /bin/bash
          echo $dxjt8416 | jq -r .oah8 | /bin/bash

